# Generated by Django 3.0.3 on 2020-05-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrdashapp', '0005_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
